package com.shahin.movieapp

object Versions {
    const val coreKtx = "1.6.0"
    const val appCompat = "1.3.1"
    const val legacySupport = "1.0.0"
    const val navigation = "2.3.5"
    const val gradle = "7.0.0"
    const val ktlint = "0.37.2"
    const val kotlin = "1.5.31"
    const val coroutines = "1.5.2"
    const val gradleVersions = "0.39.0"
    const val lifecycleVersion = "2.2.0"
    const val archTest = "2.1.0"
    const val material = "1.4.0"
    const val annotation = "1.3.0"
    const val constraintLayout = "2.1.1"
    const val room = "2.3.0"
    const val dagger = "2.40"
    const val okHttp = "4.9.2"
    const val gson = "2.8.7"
    const val retrofit = "2.9.0"
    const val stetho = "1.6.0"
    const val glide = "4.12.0"
    const val lottie = "3.4.1"
    const val junit = "4.13.2"
    const val extJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val testRunner = "1.2.0"
    const val testCore = "1.4.0"
    const val mockitoKotlin = "4.0.0"
    const val mockitoCore = "4.0.0"
    const val robolectric = "4.6.1"
    const val hamcrest = "2.2"
}